project_id = "fopcwyxqsimidisvakam"

[functions.scb-fetch]
verify_jwt = false

[functions.kpi-api]
verify_jwt = false

[functions.kpi-ingest]
verify_jwt = false

[functions.kpi-forecast]
verify_jwt = false

[functions.kpi-decisions]
verify_jwt = false

[functions.prioritize-actions]
verify_jwt = false

[functions.analyze-kpi]
verify_jwt = false

[functions.kolada-ingest]
verify_jwt = false

[functions.svk-ingest]
verify_jwt = false
