/**
 * UCE SEED DATA — Multi-domain example claims
 */

import type { UniversalClaim, ClaimEvidence } from './types';

export const SEED_CLAIMS: Omit<UniversalClaim, 'id' | 'created_at' | 'updated_at'>[] = [
  // ── HEALTH ──
  {
    claim_code: 'HLTH-001',
    domain: 'health',
    subject_entity: 'adult humans',
    variable_or_intervention: 'resistance training',
    relationship_type: 'increases',
    target_outcome: 'muscle mass',
    effect_size: 1.2,
    effect_size_unit: 'kg over 12 weeks',
    population_scope: 'men age 25-50',
    geographic_scope: 'global',
    time_scale: '12 weeks',
    status: 'supported',
    confidence_score: 0.87,
    evidence_quality: 'high',
    limitations: ['Heterogeneity in training protocols'],
    version: 1,
    statement: 'Resistance training increases muscle mass by ~1.2 kg over 12 weeks in men aged 25-50',
  },
  {
    claim_code: 'HLTH-002',
    domain: 'health',
    subject_entity: 'adult humans',
    variable_or_intervention: 'aerobic exercise',
    relationship_type: 'increases',
    target_outcome: 'mitochondrial density',
    effect_size: 0.35,
    effect_size_unit: 'fold increase',
    population_scope: 'adults 18-65',
    geographic_scope: 'global',
    time_scale: '8-16 weeks',
    status: 'supported',
    confidence_score: 0.82,
    evidence_quality: 'high',
    limitations: ['Biopsy-based measurement variability'],
    version: 1,
    statement: 'Aerobic exercise increases mitochondrial density in skeletal muscle',
  },
  {
    claim_code: 'HLTH-003',
    domain: 'health',
    subject_entity: 'adult humans',
    variable_or_intervention: 'mitochondrial density',
    relationship_type: 'increases',
    target_outcome: 'metabolic health',
    population_scope: 'adults',
    geographic_scope: 'global',
    time_scale: 'chronic',
    status: 'supported',
    confidence_score: 0.78,
    evidence_quality: 'moderate',
    limitations: ['Observational evidence primarily'],
    version: 1,
    statement: 'Higher mitochondrial density is associated with improved metabolic health',
  },
  {
    claim_code: 'HLTH-004',
    domain: 'health',
    subject_entity: 'adult humans',
    variable_or_intervention: 'metabolic health',
    relationship_type: 'increases',
    target_outcome: 'longevity',
    population_scope: 'general population',
    geographic_scope: 'global',
    time_scale: 'decades',
    status: 'supported',
    confidence_score: 0.75,
    evidence_quality: 'moderate',
    limitations: ['Confounding with lifestyle factors'],
    version: 1,
    statement: 'Better metabolic health is associated with increased longevity',
  },

  // ── PSYCHOLOGY ──
  {
    claim_code: 'PSYC-001',
    domain: 'psychology',
    subject_entity: 'adult humans',
    variable_or_intervention: 'sleep deprivation',
    relationship_type: 'decreases',
    target_outcome: 'cognitive performance',
    effect_size: -0.45,
    effect_size_unit: 'standard deviations',
    population_scope: 'adults 18-60',
    geographic_scope: 'global',
    time_scale: '24-48 hours',
    status: 'supported',
    confidence_score: 0.91,
    evidence_quality: 'very_high',
    limitations: ['Lab vs real-world settings'],
    version: 1,
    statement: 'Sleep deprivation (24-48h) decreases cognitive performance by ~0.45 SD',
  },
  {
    claim_code: 'PSYC-002',
    domain: 'psychology',
    subject_entity: 'adult humans',
    variable_or_intervention: 'cognitive performance',
    relationship_type: 'increases',
    target_outcome: 'productivity',
    population_scope: 'knowledge workers',
    geographic_scope: 'global',
    time_scale: 'daily',
    status: 'supported',
    confidence_score: 0.72,
    evidence_quality: 'moderate',
    limitations: ['Productivity measurement varies'],
    version: 1,
    statement: 'Higher cognitive performance is associated with increased workplace productivity',
  },

  // ── ECONOMICS ──
  {
    claim_code: 'ECON-001',
    domain: 'economics',
    subject_entity: 'national economies',
    variable_or_intervention: 'interest rates',
    relationship_type: 'increases',
    target_outcome: 'borrowing cost',
    population_scope: 'all borrowers',
    geographic_scope: 'global',
    time_scale: 'immediate to 6 months',
    status: 'supported',
    confidence_score: 0.95,
    evidence_quality: 'very_high',
    limitations: ['Transmission lag varies'],
    version: 1,
    statement: 'Higher interest rates increase borrowing costs for households and firms',
  },
  {
    claim_code: 'ECON-002',
    domain: 'economics',
    subject_entity: 'firms',
    variable_or_intervention: 'borrowing cost',
    relationship_type: 'decreases',
    target_outcome: 'investment',
    effect_size: -0.12,
    effect_size_unit: 'elasticity',
    population_scope: 'all firms',
    geographic_scope: 'OECD',
    time_scale: '6-18 months',
    status: 'supported',
    confidence_score: 0.80,
    evidence_quality: 'high',
    limitations: ['Varies by sector and firm size'],
    version: 1,
    statement: 'Higher borrowing costs decrease firm investment (elasticity ~-0.12)',
  },

  // ── SOCIETY ──
  {
    claim_code: 'SOC-001',
    domain: 'society',
    subject_entity: 'populations',
    variable_or_intervention: 'income inequality',
    relationship_type: 'increases',
    target_outcome: 'crime rate',
    effect_size: 0.20,
    effect_size_unit: 'correlation coefficient',
    population_scope: 'general population',
    geographic_scope: 'global',
    time_scale: 'years',
    status: 'contested',
    confidence_score: 0.58,
    evidence_quality: 'moderate',
    limitations: ['Many confounders', 'Definition of crime varies'],
    version: 1,
    statement: 'Higher income inequality is associated with increased crime rates (r ≈ 0.20)',
  },

  // ── ENVIRONMENT ──
  {
    claim_code: 'ENV-001',
    domain: 'environment',
    subject_entity: 'global atmosphere',
    variable_or_intervention: 'CO2 emissions',
    relationship_type: 'increases',
    target_outcome: 'global temperature',
    effect_size: 3.0,
    effect_size_unit: '°C per doubling of CO2',
    population_scope: 'global',
    geographic_scope: 'global',
    time_scale: 'decades to centuries',
    status: 'supported',
    confidence_score: 0.93,
    evidence_quality: 'very_high',
    limitations: ['Climate sensitivity range uncertainty'],
    version: 1,
    statement: 'CO2 emissions increase global temperature with equilibrium climate sensitivity ~3°C',
  },

  // ── CROSS-DOMAIN: Economics ↔ Health ──
  {
    claim_code: 'CROSS-001',
    domain: 'economics',
    subject_entity: 'populations',
    variable_or_intervention: 'unemployment rate',
    relationship_type: 'increases',
    target_outcome: 'mental health disorders',
    effect_size: 0.15,
    effect_size_unit: 'relative risk increase per % unemployment',
    population_scope: 'working-age adults',
    geographic_scope: 'Europe',
    time_scale: '1-3 years',
    status: 'supported',
    confidence_score: 0.71,
    evidence_quality: 'moderate',
    limitations: ['Reverse causation possible'],
    version: 1,
    statement: 'Rising unemployment increases prevalence of mental health disorders',
  },
];

export const SEED_EVIDENCE: Omit<ClaimEvidence, 'id' | 'created_at'>[] = [
  // Evidence for HLTH-001
  {
    claim_id: '', // Will be linked after insert
    evidence_type: 'meta_analysis',
    link_type: 'supports',
    source_title: 'Dose-response relationship between resistance training volume and muscle hypertrophy',
    source_authors: 'Schoenfeld BJ et al.',
    source_year: 2017,
    source_journal: 'Journal of Sports Sciences',
    strength: 0.85,
    sample_size: 1847,
    replication_weight: 1.5,
    bias_flags: [],
  },
  {
    claim_id: '',
    evidence_type: 'rct',
    link_type: 'supports',
    source_title: 'Resistance training-induced muscle hypertrophy: a systematic review',
    source_authors: 'Morton RW et al.',
    source_year: 2018,
    source_journal: 'British Journal of Sports Medicine',
    strength: 0.80,
    sample_size: 1893,
    replication_weight: 1.3,
    bias_flags: [],
  },
  // Evidence for PSYC-001
  {
    claim_id: '',
    evidence_type: 'systematic_review',
    link_type: 'supports',
    source_title: 'Sleep deprivation and cognitive performance: meta-analysis',
    source_authors: 'Lim J, Dinges DF',
    source_year: 2010,
    source_journal: 'Sleep',
    strength: 0.92,
    sample_size: 5234,
    replication_weight: 2.0,
    bias_flags: [],
  },
  // Evidence for ECON-001
  {
    claim_id: '',
    evidence_type: 'statistical_dataset',
    link_type: 'supports',
    source_title: 'Federal Reserve monetary policy transmission data',
    source_organization: 'Federal Reserve',
    source_year: 2024,
    strength: 0.95,
    sample_size: 10000,
    replication_weight: 2.0,
    bias_flags: [],
  },
];
