/**
 * OCA SEED DATA — Initial registry entries
 * 
 * The foundational concepts that bootstrap the ontology.
 */

import type { OCARegistryEntry, OCARelationship } from './types';

export const OCA_SEED_REGISTRY: OCARegistryEntry[] = [
  // ── ENTITIES ──
  {
    id: 'oca:entity:human',
    object_type: 'entity',
    code: 'ENT_HUMAN',
    name: 'Human Individual',
    definition: 'A single member of Homo sapiens, identifiable by biological and social characteristics',
    domain: 'health',
    semantic_hash: 'a1b2c3d4e5f6',
    validation_status: 'frozen',
    first_source: 'WHO',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:entity:population',
    object_type: 'entity',
    code: 'ENT_POPULATION',
    name: 'Population Group',
    definition: 'A defined group of individuals sharing geographic, demographic, or categorical characteristics',
    domain: 'demography',
    semantic_hash: 'b2c3d4e5f6a1',
    validation_status: 'frozen',
    first_source: 'UN DESA',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:entity:country',
    object_type: 'entity',
    code: 'ENT_COUNTRY',
    name: 'Sovereign State',
    definition: 'A politically organized body of people under a single government, recognized internationally',
    domain: 'governance',
    semantic_hash: 'c3d4e5f6a1b2',
    validation_status: 'frozen',
    first_source: 'ISO 3166',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:entity:economy',
    object_type: 'entity',
    code: 'ENT_ECONOMY',
    name: 'Economy',
    definition: 'The system of production, distribution, and consumption of goods and services within a defined scope',
    domain: 'economics',
    semantic_hash: 'd4e5f6a1b2c3',
    validation_status: 'frozen',
    first_source: 'World Bank',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:entity:ecosystem',
    object_type: 'entity',
    code: 'ENT_ECOSYSTEM',
    name: 'Ecosystem',
    definition: 'A biological community of interacting organisms and their physical environment',
    domain: 'environment',
    semantic_hash: 'e5f6a1b2c3d4',
    validation_status: 'frozen',
    first_source: 'UNEP',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:entity:cell',
    object_type: 'entity',
    code: 'ENT_CELL',
    name: 'Biological Cell',
    definition: 'The smallest structural and functional unit of an organism',
    domain: 'health',
    semantic_hash: 'f6a1b2c3d4e5',
    validation_status: 'frozen',
    first_source: 'NIH',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },

  // ── VARIABLES ──
  {
    id: 'oca:variable:blood_pressure',
    object_type: 'variable',
    code: 'VAR_BLOOD_PRESSURE',
    name: 'Blood Pressure',
    definition: 'The pressure of circulating blood against the walls of blood vessels, measured as systolic/diastolic mmHg',
    domain: 'health',
    semantic_hash: 'var_bp_001',
    validation_status: 'frozen',
    first_source: 'WHO',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:variable:gdp_growth',
    object_type: 'variable',
    code: 'VAR_GDP_GROWTH',
    name: 'GDP Growth Rate',
    definition: 'Annual percentage change in gross domestic product at constant prices',
    domain: 'economics',
    semantic_hash: 'var_gdp_001',
    validation_status: 'frozen',
    first_source: 'World Bank',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:variable:sleep_duration',
    object_type: 'variable',
    code: 'VAR_SLEEP_DURATION',
    name: 'Sleep Duration',
    definition: 'Total time spent in physiological sleep state per 24-hour period, measured in hours',
    domain: 'health',
    semantic_hash: 'var_sleep_001',
    validation_status: 'frozen',
    first_source: 'NIH',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:variable:cortisol',
    object_type: 'variable',
    code: 'VAR_CORTISOL',
    name: 'Cortisol Level',
    definition: 'Concentration of cortisol hormone in blood serum, measured in nmol/L',
    domain: 'health',
    semantic_hash: 'var_cortisol_001',
    validation_status: 'frozen',
    first_source: 'NIH',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:variable:inflammation',
    object_type: 'variable',
    code: 'VAR_INFLAMMATION',
    name: 'Systemic Inflammation',
    definition: 'Level of chronic low-grade inflammation measured via C-reactive protein (CRP) in mg/L',
    domain: 'health',
    semantic_hash: 'var_inflam_001',
    validation_status: 'frozen',
    first_source: 'WHO',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:variable:co2_emissions',
    object_type: 'variable',
    code: 'VAR_CO2_EMISSIONS',
    name: 'CO₂ Emissions',
    definition: 'Total carbon dioxide emissions from fossil fuel combustion and industrial processes, measured in metric tons per capita',
    domain: 'environment',
    semantic_hash: 'var_co2_001',
    validation_status: 'frozen',
    first_source: 'OWID',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:variable:life_expectancy',
    object_type: 'variable',
    code: 'VAR_LIFE_EXPECTANCY',
    name: 'Life Expectancy at Birth',
    definition: 'Average number of years a newborn would live if current mortality rates persisted, measured in years',
    domain: 'demography',
    semantic_hash: 'var_lifeexp_001',
    validation_status: 'frozen',
    first_source: 'WHO',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:variable:unemployment',
    object_type: 'variable',
    code: 'VAR_UNEMPLOYMENT',
    name: 'Unemployment Rate',
    definition: 'Percentage of the labor force that is jobless and actively seeking employment',
    domain: 'economics',
    semantic_hash: 'var_unemp_001',
    validation_status: 'frozen',
    first_source: 'ILO',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:variable:cognitive_performance',
    object_type: 'variable',
    code: 'VAR_COGNITIVE_PERF',
    name: 'Cognitive Performance',
    definition: 'Composite measure of cognitive function including memory, attention, and executive function',
    domain: 'psychology',
    semantic_hash: 'var_cogperf_001',
    validation_status: 'validated',
    first_source: 'APA',
    created_at: '2026-01-01T00:00:00Z',
  },

  // ── INTERVENTIONS ──
  {
    id: 'oca:intervention:exercise',
    object_type: 'intervention',
    code: 'INT_EXERCISE',
    name: 'Physical Exercise',
    definition: 'Structured, repetitive physical activity performed to improve or maintain physical fitness',
    domain: 'health',
    semantic_hash: 'int_exercise_001',
    validation_status: 'frozen',
    first_source: 'WHO',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:intervention:tax_reform',
    object_type: 'intervention',
    code: 'INT_TAX_REFORM',
    name: 'Tax Reform',
    definition: 'Systematic modification of tax rates, brackets, or collection methods by government authority',
    domain: 'economics',
    semantic_hash: 'int_tax_001',
    validation_status: 'validated',
    first_source: 'OECD',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'oca:intervention:sleep_extension',
    object_type: 'intervention',
    code: 'INT_SLEEP_EXT',
    name: 'Sleep Extension',
    definition: 'Deliberate increase in total sleep duration through behavioral or environmental changes',
    domain: 'health',
    semantic_hash: 'int_sleepext_001',
    validation_status: 'frozen',
    first_source: 'NIH',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },
  {
    id: 'oca:intervention:diet_change',
    object_type: 'intervention',
    code: 'INT_DIET_CHANGE',
    name: 'Dietary Modification',
    definition: 'Systematic alteration of food intake patterns, composition, or quantity',
    domain: 'nutrition',
    semantic_hash: 'int_diet_001',
    validation_status: 'frozen',
    first_source: 'WHO',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-15T00:00:00Z',
  },

  // ── RELATIONSHIPS (as registry entries) ──
  {
    id: 'oca:relationship:increases',
    object_type: 'relationship',
    code: 'REL_INCREASES',
    name: 'Increases',
    definition: 'Source variable or intervention causes a measurable increase in target variable',
    domain: 'health',
    semantic_hash: 'rel_inc_001',
    validation_status: 'frozen',
    first_source: 'SYSTEM',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'oca:relationship:decreases',
    object_type: 'relationship',
    code: 'REL_DECREASES',
    name: 'Decreases',
    definition: 'Source variable or intervention causes a measurable decrease in target variable',
    domain: 'health',
    semantic_hash: 'rel_dec_001',
    validation_status: 'frozen',
    first_source: 'SYSTEM',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'oca:relationship:correlates_with',
    object_type: 'relationship',
    code: 'REL_CORRELATES',
    name: 'Correlates With',
    definition: 'Statistical co-movement observed without established causal mechanism',
    domain: 'health',
    semantic_hash: 'rel_corr_001',
    validation_status: 'frozen',
    first_source: 'SYSTEM',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'oca:relationship:causes',
    object_type: 'relationship',
    code: 'REL_CAUSES',
    name: 'Causes',
    definition: 'Established causal relationship supported by RCT or quasi-experimental evidence',
    domain: 'health',
    semantic_hash: 'rel_cause_001',
    validation_status: 'frozen',
    first_source: 'SYSTEM',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'oca:relationship:moderates',
    object_type: 'relationship',
    code: 'REL_MODERATES',
    name: 'Moderates',
    definition: 'Source changes the strength or direction of the relationship between two other variables',
    domain: 'health',
    semantic_hash: 'rel_mod_001',
    validation_status: 'frozen',
    first_source: 'SYSTEM',
    created_at: '2026-01-01T00:00:00Z',
    frozen_at: '2026-01-01T00:00:00Z',
  },
];

// Pre-defined causal relationships for seed
export const OCA_SEED_RELATIONSHIPS: OCARelationship[] = [
  {
    id: 'rel-exercise-bp',
    relationship_type: 'decreases',
    source_type: 'intervention',
    source_id: 'oca:intervention:exercise',
    target_type: 'variable',
    target_id: 'oca:variable:blood_pressure',
    strength: 0.7,
    confidence: 0.85,
    evidence_level: 'meta_analysis',
    temporal_delay_days: 42,
    is_causal: true,
    mechanism_description: 'Improved endothelial function and reduced peripheral vascular resistance',
    ontology_version: '1.0.0',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rel-exercise-inflammation',
    relationship_type: 'decreases',
    source_type: 'intervention',
    source_id: 'oca:intervention:exercise',
    target_type: 'variable',
    target_id: 'oca:variable:inflammation',
    strength: 0.65,
    confidence: 0.8,
    evidence_level: 'meta_analysis',
    temporal_delay_days: 56,
    is_causal: true,
    mechanism_description: 'Release of anti-inflammatory myokines during muscle contraction',
    ontology_version: '1.0.0',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rel-sleep-cortisol',
    relationship_type: 'decreases',
    source_type: 'intervention',
    source_id: 'oca:intervention:sleep_extension',
    target_type: 'variable',
    target_id: 'oca:variable:cortisol',
    strength: 0.6,
    confidence: 0.75,
    evidence_level: 'rct',
    temporal_delay_days: 14,
    is_causal: true,
    mechanism_description: 'Extended sleep normalizes HPA axis regulation',
    ontology_version: '1.0.0',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rel-sleep-cognition',
    relationship_type: 'increases',
    source_type: 'intervention',
    source_id: 'oca:intervention:sleep_extension',
    target_type: 'variable',
    target_id: 'oca:variable:cognitive_performance',
    strength: 0.7,
    confidence: 0.82,
    evidence_level: 'rct',
    temporal_delay_days: 7,
    is_causal: true,
    mechanism_description: 'Enhanced memory consolidation and synaptic homeostasis during sleep',
    ontology_version: '1.0.0',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rel-cortisol-inflammation',
    relationship_type: 'increases',
    source_type: 'variable',
    source_id: 'oca:variable:cortisol',
    target_type: 'variable',
    target_id: 'oca:variable:inflammation',
    strength: 0.55,
    confidence: 0.7,
    evidence_level: 'cohort_study',
    temporal_delay_days: 90,
    population_scope: 'chronic elevation only',
    is_causal: false,
    mechanism_description: 'Chronic cortisol elevation impairs immune regulation',
    ontology_version: '1.0.0',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rel-unemployment-cortisol',
    relationship_type: 'increases',
    source_type: 'variable',
    source_id: 'oca:variable:unemployment',
    target_type: 'variable',
    target_id: 'oca:variable:cortisol',
    strength: 0.5,
    confidence: 0.65,
    evidence_level: 'cohort_study',
    temporal_delay_days: 30,
    is_causal: false,
    mechanism_description: 'Economic stress activates HPA axis via psychological distress',
    ontology_version: '1.0.0',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: 'rel-inflammation-lifeexp',
    relationship_type: 'decreases',
    source_type: 'variable',
    source_id: 'oca:variable:inflammation',
    target_type: 'variable',
    target_id: 'oca:variable:life_expectancy',
    strength: 0.6,
    confidence: 0.75,
    evidence_level: 'meta_analysis',
    temporal_delay_days: 3650,
    is_causal: false,
    mechanism_description: 'Chronic inflammation accelerates cellular aging and disease onset',
    ontology_version: '1.0.0',
    created_at: '2026-01-01T00:00:00Z',
  },
];
