/**
 * GLOBAL INDEX REGISTRY
 * 
 * Definitioner för alla index som används som sensorer.
 * Varje index har strikt definierad beräkningsmetod och normalisering.
 */

import type { IndexDefinition, IndexCategory, IndexCode } from './index-types';

// =============================================================================
// LIVING BASIC INDICES
// =============================================================================

const LIVING_BASIC_INDICES: IndexDefinition[] = [
  {
    code: 'BIG_MAC_INDEX',
    category: 'living_basic',
    name_en: 'Big Mac Index',
    name_sv: 'Big Mac-index',
    description: 'Köpkraftsparitet mätt genom priset på en Big Mac, justerat för lokala löner.',
    formula_description: '(Big Mac pris i lokal valuta / Medianinkomst per timme) × 100',
    input_indicators: ['big_mac_price_local', 'median_hourly_wage', 'exchange_rate_usd'],
    normalization_method: 'ppp_adjusted',
    optimal_range: { min: 0.8, max: 1.2 },
    direction: 'neutral_optimal',
    update_frequency: 'quarterly',
    primary_sources: ['The Economist', 'ILO', 'National Statistics Offices'],
    coverage_start_year: 1986,
    geo_coverage: 'global',
  },
  {
    code: 'STAPLE_FOOD_INDEX',
    category: 'living_basic',
    name_en: 'Staple Food Affordability Index',
    name_sv: 'Baslivsmedelsindex',
    description: 'Kostnad för 2000 kcal/dag från baslivsmedel som andel av dagsinkomst.',
    formula_description: '(Kostnad för 2000 kcal basmat / Dagsinkomst efter skatt) × 100',
    input_indicators: ['bread_price', 'rice_price', 'potato_price', 'milk_price', 'egg_price', 'median_daily_income'],
    normalization_method: 'ppp_adjusted',
    optimal_range: { min: 0, max: 15 },
    direction: 'lower_better',
    update_frequency: 'monthly',
    primary_sources: ['FAO', 'World Bank', 'National Consumer Price Indices'],
    coverage_start_year: 1990,
    geo_coverage: 'global',
  },
  {
    code: 'HOUSING_AFFORDABILITY_INDEX',
    category: 'living_basic',
    name_en: 'Housing Affordability Index',
    name_sv: 'Bostadstillgänglighetsindex',
    description: 'Medianbostadens pris/hyra i relation till medianinkomst.',
    formula_description: 'Median housing cost / Median annual household income',
    input_indicators: ['median_house_price', 'median_rent', 'median_household_income'],
    normalization_method: 'zscore',
    optimal_range: { min: 2.5, max: 4.0 },
    direction: 'lower_better',
    update_frequency: 'quarterly',
    primary_sources: ['OECD', 'National Housing Statistics', 'Numbeo'],
    coverage_start_year: 1970,
    geo_coverage: 'oecd',
  },
  {
    code: 'ENERGY_COST_INDEX',
    category: 'living_basic',
    name_en: 'Household Energy Cost Index',
    name_sv: 'Energikostnadsindex',
    description: 'Total energikostnad (el, värme, drivmedel) som andel av disponibel inkomst.',
    formula_description: '(El + Värme + Transport-energi) / Disponibel inkomst × 100',
    input_indicators: ['electricity_price_kwh', 'heating_cost', 'fuel_price', 'avg_consumption', 'disposable_income'],
    normalization_method: 'ppp_adjusted',
    optimal_range: { min: 0, max: 10 },
    direction: 'lower_better',
    update_frequency: 'monthly',
    primary_sources: ['IEA', 'Eurostat', 'National Energy Agencies'],
    coverage_start_year: 1980,
    geo_coverage: 'global',
  },
  {
    code: 'TRANSPORT_INDEX',
    category: 'living_basic',
    name_en: 'Transport Accessibility Index',
    name_sv: 'Transportindex',
    description: 'Pendlingskostnad och tillgänglighet till arbete/service.',
    formula_description: 'Weighted average of (commute_cost + time_cost + accessibility_score)',
    input_indicators: ['avg_commute_cost', 'avg_commute_time', 'public_transport_coverage', 'car_ownership_necessity'],
    normalization_method: 'minmax',
    optimal_range: { min: 70, max: 100 },
    direction: 'higher_better',
    update_frequency: 'annual',
    primary_sources: ['ITF', 'National Transport Statistics', 'TomTom Traffic Index'],
    coverage_start_year: 2000,
    geo_coverage: 'oecd',
  },
  {
    code: 'TIME_COST_INDEX',
    category: 'living_basic',
    name_en: 'Time Cost of Living Index',
    name_sv: 'Tidskostnadsindex',
    description: 'Arbetstid som krävs för att upprätthålla basal levnadsstandard.',
    formula_description: 'Hours worked per week to afford: housing + food + energy + transport + healthcare',
    input_indicators: ['housing_hours', 'food_hours', 'energy_hours', 'transport_hours', 'healthcare_hours'],
    normalization_method: 'zscore',
    optimal_range: { min: 20, max: 35 },
    direction: 'lower_better',
    update_frequency: 'annual',
    primary_sources: ['ILO', 'OECD', 'National Time Use Surveys'],
    coverage_start_year: 1995,
    geo_coverage: 'oecd',
  },
];

// =============================================================================
// SHADOW ECONOMY INDICES
// =============================================================================

const SHADOW_ECONOMY_INDICES: IndexDefinition[] = [
  {
    code: 'INFORMAL_MARKET_INDEX',
    category: 'shadow_economy',
    name_en: 'Informal Market Activity Index',
    name_sv: 'Informell marknadsindex',
    description: 'Uppskattad storlek på informell/svart ekonomi som andel av BNP.',
    formula_description: 'Estimated informal economy / Official GDP × 100',
    input_indicators: ['currency_demand_deviation', 'electricity_consumption_gap', 'labor_force_discrepancy'],
    normalization_method: 'percentile',
    optimal_range: { min: 0, max: 15 },
    direction: 'lower_better',
    update_frequency: 'annual',
    primary_sources: ['IMF Shadow Economy Estimates', 'World Bank', 'Academic Studies'],
    coverage_start_year: 1990,
    geo_coverage: 'global',
  },
  {
    code: 'CORRUPTION_FRICTION_INDEX',
    category: 'shadow_economy',
    name_en: 'Corruption Friction Index',
    name_sv: 'Korruptionsfriktionsindex',
    description: 'Uppskattad resursförlust genom korruption och ineffektivitet.',
    formula_description: 'Composite of bribery rates, procurement leakage, regulatory capture indicators',
    input_indicators: ['bribery_prevalence', 'procurement_overpricing', 'regulatory_capture_score', 'audit_discrepancies'],
    normalization_method: 'percentile',
    optimal_range: { min: 0, max: 5 },
    direction: 'lower_better',
    update_frequency: 'annual',
    primary_sources: ['Transparency International', 'World Bank', 'GRECO'],
    coverage_start_year: 1995,
    geo_coverage: 'global',
  },
  {
    code: 'PARALLEL_ECONOMY_INDEX',
    category: 'shadow_economy',
    name_en: 'Parallel Economy Indicator',
    name_sv: 'Parallellekonomiskt index',
    description: 'Indikator på ekonomisk desperation och alternativa marknader.',
    formula_description: 'Composite signal from informal labor, unreported transactions, alternative currencies',
    input_indicators: ['informal_employment_rate', 'cash_economy_indicators', 'barter_prevalence'],
    normalization_method: 'zscore',
    optimal_range: { min: -1, max: 1 },
    direction: 'neutral_optimal',
    update_frequency: 'annual',
    primary_sources: ['ILO', 'Central Banks', 'Academic Research'],
    coverage_start_year: 2000,
    geo_coverage: 'global',
  },
];

// =============================================================================
// HEALTH & FUNCTION INDICES
// =============================================================================

const HEALTH_FUNCTION_INDICES: IndexDefinition[] = [
  {
    code: 'LIFE_EXPECTANCY_QUALITY_ADJUSTED',
    category: 'health_function',
    name_en: 'Quality-Adjusted Life Expectancy',
    name_sv: 'Kvalitetsjusterad livslängd',
    description: 'Förväntad livslängd justerad för hälsorelaterad livskvalitet (QALY).',
    formula_description: 'Life expectancy × Average health utility score',
    input_indicators: ['life_expectancy_at_birth', 'healthy_life_years', 'disability_prevalence'],
    normalization_method: 'minmax',
    optimal_range: { min: 70, max: 85 },
    direction: 'higher_better',
    update_frequency: 'annual',
    primary_sources: ['WHO', 'IHME Global Burden of Disease', 'National Health Statistics'],
    coverage_start_year: 1950,
    geo_coverage: 'global',
  },
  {
    code: 'METABOLIC_DISEASE_INDEX',
    category: 'health_function',
    name_en: 'Metabolic Disease Burden Index',
    name_sv: 'Metabol sjukdomsindex',
    description: 'Prevalens av metabola sjukdomar (diabetes, obesitas, hjärt-kärl).',
    formula_description: 'Weighted prevalence of diabetes + obesity + cardiovascular disease',
    input_indicators: ['diabetes_prevalence', 'obesity_rate', 'cvd_mortality_rate', 'metabolic_syndrome_prevalence'],
    normalization_method: 'zscore',
    optimal_range: { min: -1, max: 0 },
    direction: 'lower_better',
    update_frequency: 'annual',
    primary_sources: ['WHO', 'IHME', 'National Health Surveys'],
    coverage_start_year: 1980,
    geo_coverage: 'global',
  },
  {
    code: 'MENTAL_HEALTH_INDEX',
    category: 'health_function',
    name_en: 'Mental Health Burden Index',
    name_sv: 'Psykisk ohälsoindex',
    description: 'Prevalens och samhällskostnad för psykisk ohälsa.',
    formula_description: 'Composite of depression, anxiety, suicide rates, treatment gap',
    input_indicators: ['depression_prevalence', 'anxiety_prevalence', 'suicide_rate', 'mental_health_treatment_gap'],
    normalization_method: 'zscore',
    optimal_range: { min: -1, max: 0 },
    direction: 'lower_better',
    update_frequency: 'annual',
    primary_sources: ['WHO', 'OECD Health', 'National Mental Health Surveys'],
    coverage_start_year: 1990,
    geo_coverage: 'global',
  },
  {
    code: 'SUBSTANCE_PREVALENCE_INDEX',
    category: 'health_function',
    name_en: 'Substance Use Prevalence Index',
    name_sv: 'Substansbruksprevalensindex',
    description: 'Prevalens av problematiskt substansbruk och beroende.',
    formula_description: 'Weighted prevalence of alcohol use disorder + drug use disorder + tobacco',
    input_indicators: ['alcohol_use_disorder_prevalence', 'drug_use_disorder_prevalence', 'tobacco_prevalence', 'overdose_rate'],
    normalization_method: 'zscore',
    optimal_range: { min: -1, max: 0 },
    direction: 'lower_better',
    update_frequency: 'annual',
    primary_sources: ['WHO', 'UNODC', 'EMCDDA', 'National Substance Use Surveys'],
    coverage_start_year: 1990,
    geo_coverage: 'global',
  },
  {
    code: 'HEALTHCARE_EFFICIENCY_INDEX',
    category: 'health_function',
    name_en: 'Healthcare System Efficiency Index',
    name_sv: 'Sjukvårdseffektivitetsindex',
    description: 'Hälsoutfall per investerad resurs i sjukvårdssystemet.',
    formula_description: 'Health outcomes index / Healthcare spending per capita (PPP adjusted)',
    input_indicators: ['health_outcomes_composite', 'healthcare_spending_per_capita', 'avoidable_mortality'],
    normalization_method: 'percentile',
    optimal_range: { min: 70, max: 100 },
    direction: 'higher_better',
    update_frequency: 'annual',
    primary_sources: ['WHO', 'OECD Health Data', 'Commonwealth Fund'],
    coverage_start_year: 1970,
    geo_coverage: 'oecd',
  },
];

// =============================================================================
// SOCIAL & CULTURAL INDICES
// =============================================================================

const SOCIAL_CULTURAL_INDICES: IndexDefinition[] = [
  {
    code: 'FAMILY_FORMATION_INDEX',
    category: 'social_cultural',
    name_en: 'Family Formation Index',
    name_sv: 'Familjebildningsindex',
    description: 'Möjlighet och benägenhet att bilda familj.',
    formula_description: 'Composite of marriage rate, cohabitation rate, first child age, desired vs actual family size',
    input_indicators: ['marriage_rate', 'median_first_child_age', 'desired_family_size', 'actual_family_size'],
    normalization_method: 'zscore',
    optimal_range: { min: -0.5, max: 0.5 },
    direction: 'neutral_optimal',
    update_frequency: 'annual',
    primary_sources: ['UN Population Division', 'Eurostat', 'National Demographic Surveys'],
    coverage_start_year: 1960,
    geo_coverage: 'global',
  },
  {
    code: 'FERTILITY_INDEX',
    category: 'social_cultural',
    name_en: 'Fertility Rate Index',
    name_sv: 'Fertilitetsindex',
    description: 'Total fertilitet i relation till ersättningsnivå.',
    formula_description: 'Total Fertility Rate / 2.1 (replacement level)',
    input_indicators: ['total_fertility_rate', 'age_specific_fertility_rates', 'childlessness_rate'],
    normalization_method: 'minmax',
    optimal_range: { min: 0.9, max: 1.1 },
    direction: 'neutral_optimal',
    update_frequency: 'annual',
    primary_sources: ['UN Population Division', 'World Bank', 'National Statistics'],
    coverage_start_year: 1950,
    geo_coverage: 'global',
  },
  {
    code: 'LONELINESS_INDEX',
    category: 'social_cultural',
    name_en: 'Social Isolation Index',
    name_sv: 'Ensamhetsindex',
    description: 'Prevalens av ensamhet och social isolering.',
    formula_description: 'Composite of self-reported loneliness, single households, social contact frequency',
    input_indicators: ['loneliness_prevalence', 'single_person_households', 'social_contact_frequency', 'community_participation'],
    normalization_method: 'zscore',
    optimal_range: { min: -1, max: 0 },
    direction: 'lower_better',
    update_frequency: 'annual',
    primary_sources: ['ESS', 'Gallup World Poll', 'National Social Surveys'],
    coverage_start_year: 2000,
    geo_coverage: 'oecd',
  },
  {
    code: 'SOCIAL_TRUST_INDEX',
    category: 'social_cultural',
    name_en: 'Social Trust Index',
    name_sv: 'Social tillitsindex',
    description: 'Generell tillit till andra människor och samhällsinstitutioner.',
    formula_description: 'Composite of interpersonal trust, institutional trust, civic participation',
    input_indicators: ['interpersonal_trust', 'trust_in_government', 'trust_in_media', 'civic_engagement'],
    normalization_method: 'minmax',
    optimal_range: { min: 60, max: 100 },
    direction: 'higher_better',
    update_frequency: 'annual',
    primary_sources: ['World Values Survey', 'ESS', 'Edelman Trust Barometer'],
    coverage_start_year: 1980,
    geo_coverage: 'global',
  },
  {
    code: 'VIOLENCE_INDEX',
    category: 'social_cultural',
    name_en: 'Violence Prevalence Index',
    name_sv: 'Våldsindex',
    description: 'Prevalens av våld uppdelat på typ (interpersonellt, kollektivt, självriktat).',
    formula_description: 'Weighted composite of homicide, assault, domestic violence, collective violence rates',
    input_indicators: ['homicide_rate', 'assault_rate', 'domestic_violence_prevalence', 'collective_violence_deaths'],
    normalization_method: 'zscore',
    optimal_range: { min: -2, max: 0 },
    direction: 'lower_better',
    update_frequency: 'annual',
    primary_sources: ['UNODC', 'WHO', 'National Crime Statistics'],
    coverage_start_year: 1970,
    geo_coverage: 'global',
  },
];

// =============================================================================
// PRODUCTIVITY & WORK INDICES
// =============================================================================

const PRODUCTIVITY_WORK_INDICES: IndexDefinition[] = [
  {
    code: 'AUTOMATION_RISK_INDEX',
    category: 'productivity_work',
    name_en: 'Job Automation Risk Index',
    name_sv: 'Automatiseringsriskindex',
    description: 'Andel av arbetskraften i yrken med hög automatiseringsrisk.',
    formula_description: 'Weighted employment share in high-automation-risk occupations',
    input_indicators: ['employment_by_occupation', 'automation_probability_by_occupation', 'task_composition'],
    normalization_method: 'percentile',
    optimal_range: { min: 0, max: 30 },
    direction: 'neutral_optimal',
    update_frequency: 'annual',
    primary_sources: ['OECD', 'Frey & Osborne methodology', 'National Labor Statistics'],
    coverage_start_year: 2013,
    geo_coverage: 'oecd',
  },
  {
    code: 'WAGE_PRODUCTIVITY_GAP',
    category: 'productivity_work',
    name_en: 'Wage-Productivity Divergence Index',
    name_sv: 'Löne-produktivitetsgap',
    description: 'Avvikelse mellan reallöneutveckling och produktivitetstillväxt.',
    formula_description: '(Productivity growth rate - Real wage growth rate) cumulative over 10 years',
    input_indicators: ['labor_productivity_growth', 'real_wage_growth', 'labor_share_of_income'],
    normalization_method: 'zscore',
    optimal_range: { min: -5, max: 5 },
    direction: 'neutral_optimal',
    update_frequency: 'annual',
    primary_sources: ['ILO', 'OECD', 'BLS'],
    coverage_start_year: 1970,
    geo_coverage: 'oecd',
  },
  {
    code: 'ADMINISTRATIVE_OVERHEAD_INDEX',
    category: 'productivity_work',
    name_en: 'Administrative Overhead Index',
    name_sv: 'Administrativ överbyggnadsindex',
    description: 'Andel av ekonomin i administration utan mätbar produktiv output.',
    formula_description: 'Administrative employment / Total employment, adjusted for sector',
    input_indicators: ['administrative_employment_share', 'compliance_cost_gdp_share', 'bureaucracy_time_cost'],
    normalization_method: 'zscore',
    optimal_range: { min: -1, max: 1 },
    direction: 'lower_better',
    update_frequency: 'annual',
    primary_sources: ['OECD', 'World Bank Doing Business', 'National Labor Statistics'],
    coverage_start_year: 1990,
    geo_coverage: 'oecd',
  },
  {
    code: 'EDUCATION_MISMATCH_INDEX',
    category: 'productivity_work',
    name_en: 'Education-Job Mismatch Index',
    name_sv: 'Utbildningsmatchningsindex',
    description: 'Grad av över-/underutbildning i relation till faktiska jobbkrav.',
    formula_description: 'Share of workers over/under-qualified for their jobs',
    input_indicators: ['overqualification_rate', 'underqualification_rate', 'field_of_study_mismatch'],
    normalization_method: 'zscore',
    optimal_range: { min: -0.5, max: 0.5 },
    direction: 'neutral_optimal',
    update_frequency: 'annual',
    primary_sources: ['OECD PIAAC', 'Eurostat', 'National Labor Force Surveys'],
    coverage_start_year: 2000,
    geo_coverage: 'oecd',
  },
  {
    code: 'SKILL_WASTE_INDEX',
    category: 'productivity_work',
    name_en: 'Skill Underutilization Index',
    name_sv: 'Kompetensspillsindex',
    description: 'Grad av outnyttjad kompetens i arbetskraften.',
    formula_description: 'Composite of skill mismatch, underemployment, brain drain',
    input_indicators: ['skill_mismatch_rate', 'involuntary_part_time', 'brain_drain_rate', 'unemployment_by_education'],
    normalization_method: 'zscore',
    optimal_range: { min: -1, max: 0 },
    direction: 'lower_better',
    update_frequency: 'annual',
    primary_sources: ['ILO', 'OECD', 'National Skills Surveys'],
    coverage_start_year: 2000,
    geo_coverage: 'oecd',
  },
];

// =============================================================================
// COMPLETE REGISTRY
// =============================================================================

export const INDEX_REGISTRY: IndexDefinition[] = [
  ...LIVING_BASIC_INDICES,
  ...SHADOW_ECONOMY_INDICES,
  ...HEALTH_FUNCTION_INDICES,
  ...SOCIAL_CULTURAL_INDICES,
  ...PRODUCTIVITY_WORK_INDICES,
];

export function getIndexDefinition(code: IndexCode): IndexDefinition | undefined {
  return INDEX_REGISTRY.find(idx => idx.code === code);
}

export function getIndicesByCategory(category: IndexCategory): IndexDefinition[] {
  return INDEX_REGISTRY.filter(idx => idx.category === category);
}

export function getAllIndexCodes(): IndexCode[] {
  return INDEX_REGISTRY.map(idx => idx.code);
}

export const INDEX_CATEGORIES: { code: IndexCategory; name_sv: string; name_en: string }[] = [
  { code: 'living_basic', name_sv: 'Basala levnadsindex', name_en: 'Basic Living Indices' },
  { code: 'shadow_economy', name_sv: 'Skuggekonomi', name_en: 'Shadow Economy' },
  { code: 'health_function', name_sv: 'Hälsa & funktion', name_en: 'Health & Function' },
  { code: 'social_cultural', name_sv: 'Socialt & kulturellt', name_en: 'Social & Cultural' },
  { code: 'productivity_work', name_sv: 'Produktivitet & arbete', name_en: 'Productivity & Work' },
];
