-- BLOCK: Immigration & Integration Economics (Global → City)
INSERT INTO public.kpi_definitions (kpi_index, code, name, category, description, rationale, unit, is_inverted, red_flag_conditions, breakdown_dimensions, is_active)
VALUES 
  (28, 'immigration_fiscal_balance', 'Fiskal migrationspåverkan', 'ekonomisk_barkraft',
   'Nettoskillnad mellan skatter inbetalda och välfärdskostnader för utrikes födda',
   'Kvantifierar den ekonomiska nettoeffekten av migration utan värdering.',
   'SEK/person/år', false,
   '[{"condition": "Metodbyte i beräkning"}]'::jsonb,
   ARRAY['origin_region', 'residence_time', 'age', 'region', 'municipality']::text[], true),

  (29, 'immigration_employment_gap', 'Sysselsättningsgap (migration)', 'arbete_produktivitet',
   'Procentuell skillnad i sysselsättningsgrad mellan utrikes och inrikes födda',
   'Mäter arbetsmarknadsintegration över tid.',
   'procentenheter', true,
   '[{"condition": "Gap > 20 procentenheter", "threshold": "20"}]'::jsonb,
   ARRAY['residence_time', 'origin_region', 'age', 'gender', 'region']::text[], true),

  (30, 'integration_wage_convergence', 'Lönekonvergenstid', 'arbete_produktivitet',
   'Antal år till 80% av medianlön för inrikes födda',
   'Mäter ekonomisk integration på arbetsmarknaden.',
   'år', true,
   '[{"condition": "Tid > 15 år", "threshold": "15"}]'::jsonb,
   ARRAY['origin_region', 'education_level', 'sector']::text[], true),

  (31, 'second_gen_income_mobility', 'Andragenerationsmobilitet', 'ekonomisk_barkraft',
   'Inkomstkvot andrageneration vs jämnåriga med inrikes födda föräldrar',
   'Mäter långsiktig social rörlighet och integration.',
   'kvot', false,
   '[{"condition": "Kvot < 0.85", "threshold": "0.85"}]'::jsonb,
   ARRAY['parent_origin', 'education', 'region']::text[], true),

  (32, 'immigration_gdp_contribution', 'BNP-bidrag (utrikes födda)', 'ekonomisk_barkraft',
   'Andel av BNP genererad av utrikes födda arbetskraft',
   'Mäter ekonomiskt bidrag till nationalprodukt.',
   '%', false,
   '[{"condition": "Metodändring i beräkning"}]'::jsonb,
   ARRAY['sector', 'origin_region', 'residence_time']::text[], true),

  (33, 'public_finance_migration_projection', 'Fiskal 30-årsprognos (migration)', 'ekonomisk_barkraft',
   'Projicerad nettopåverkan på offentliga finanser över 30 år',
   'Långsiktig fiskal konsekvensanalys under givna antaganden.',
   'mdkr SEK', false,
   '[{"condition": "Antaganden ändrade"}]'::jsonb,
   ARRAY['scenario', 'integration_rate']::text[], true),

-- BLOCK: Energy & Climate Debate
  (34, 'energy_lcoe_comparison', 'Energikostnad (LCOE)', 'infrastruktur',
   'Utjämnad produktionskostnad per energikälla',
   'Jämför faktiska kostnader för olika energislag.',
   'öre/kWh', true,
   '[{"condition": "Metodändring"}]'::jsonb,
   ARRAY['energy_source', 'region', 'year']::text[], true),

  (35, 'grid_stability_index', 'Elnätsstabilitet', 'karnsystem_funktion',
   'Frekvensavvikelser och avbrottstid i elnätet',
   'Mäter systemstabilitet vid ökad andel variabel produktion.',
   'index 0-100', false,
   '[{"condition": "Index < 80", "threshold": "80"}]'::jsonb,
   ARRAY['region', 'season']::text[], true),

  (36, 'energy_import_dependency', 'Energiimportberoende', 'systemrisk_styrning',
   'Andel av energiförbrukning som importeras',
   'Mäter energisäkerhet och självförsörjningsgrad.',
   '%', true,
   '[{"condition": "Importandel > 50%", "threshold": "50"}]'::jsonb,
   ARRAY['energy_type', 'origin_country']::text[], true),

  (37, 'carbon_intensity_gdp', 'Koldioxidintensitet', 'infrastruktur',
   'CO2-utsläpp per enhet BNP',
   'Mäter ekonomins koldioxideffektivitet.',
   'kg CO2/1000 SEK', true,
   '[{"condition": "Ökning > 5% per år"}]'::jsonb,
   ARRAY['sector', 'region']::text[], true),

-- BLOCK: Crime & Security Reality
  (38, 'crime_per_capita_trend', 'Brottsutveckling per capita', 'social_stabilitet',
   'Anmälda brott per 100 000 invånare, 10-årstrend',
   'Kvantifierar faktisk brottsutveckling utan värdering.',
   'per 100 000', true,
   '[{"condition": "Ökning > 10% per år"}]'::jsonb,
   ARRAY['crime_type', 'region', 'municipality', 'time']::text[], true),

  (39, 'crime_clearance_rate', 'Uppklaringsgrad', 'social_stabilitet',
   'Andel anmälda brott som leder till lagföring',
   'Mäter rättssystemets effektivitet.',
   '%', false,
   '[{"condition": "Uppklaring < 15%", "threshold": "15"}]'::jsonb,
   ARRAY['crime_type', 'region']::text[], true),

  (40, 'victim_survey_gap', 'Mörkertalsindex', 'social_stabilitet',
   'Skillnad mellan offerundersökningar och anmälda brott',
   'Mäter dold brottslighet och anmälningsbenägenhet.',
   'kvot', true,
   '[{"condition": "Kvot > 3", "threshold": "3"}]'::jsonb,
   ARRAY['crime_type', 'demographic_group']::text[], true),

  (41, 'shooting_incidents', 'Skjutningar', 'social_stabilitet',
   'Bekräftade skjutningar per 100 000 invånare',
   'Mäter grovt våld och gängkriminalitet.',
   'per 100 000', true,
   '[{"condition": "Ökning > 20% per år"}]'::jsonb,
   ARRAY['region', 'municipality', 'time']::text[], true),

  (42, 'gang_violence_fatalities', 'Dödligt gängvåld', 'social_stabilitet',
   'Dödsfall kopplade till gängkonflikter per år',
   'Mäter extremvåld i kriminella nätverk.',
   'antal/år', true,
   '[{"condition": "Ökning > 25% per år"}]'::jsonb,
   ARRAY['region', 'time']::text[], true),

-- BLOCK: Welfare & Tax Efficiency
  (43, 'welfare_dependency_duration', 'Bidragsberoende-duration', 'arbete_produktivitet',
   'Mediantid i ekonomiskt bistånd innan självförsörjning',
   'Mäter välfärdssystemets effektivitet.',
   'månader', true,
   '[{"condition": "Duration > 36 månader", "threshold": "36"}]'::jsonb,
   ARRAY['age', 'origin', 'region', 'municipality']::text[], true),

  (44, 'tax_revenue_elasticity', 'Skatteintäktselasticitet', 'ekonomisk_barkraft',
   'Procentuell förändring i skatteintäkter vid 1% skattehöjning',
   'Mäter beteenderespons på skatteförändringar.',
   'koefficient', false,
   '[{"condition": "Elasticitet < 0.5", "threshold": "0.5"}]'::jsonb,
   ARRAY['income_decile', 'tax_type']::text[], true),

  (45, 'social_mobility_index', 'Social rörlighet', 'ekonomisk_barkraft',
   'Sannolikhet att barn överträffar föräldrars inkomst',
   'Mäter klassresa och meritokratisk funktion.',
   '%', false,
   '[{"condition": "Index < 40%", "threshold": "40"}]'::jsonb,
   ARRAY['parent_income_quintile', 'region']::text[], true),

-- BLOCK: Education Reality
  (46, 'pisa_score_trend', 'PISA-utveckling', 'arbete_produktivitet',
   'Poängutveckling i läsning, matematik, naturvetenskap',
   'Internationellt jämförbart kunskapsmått.',
   'poäng', false,
   '[{"condition": "Minskning > 10 poäng per 3-årscykel"}]'::jsonb,
   ARRAY['subject', 'demographic_group', 'school_type']::text[], true),

  (47, 'school_segregation_index', 'Skolsegregationsindex', 'social_stabilitet',
   'Dissimilaritetsindex för elevsammansättning',
   'Mäter geografisk och socioekonomisk skolsegregation.',
   'index 0-100', true,
   '[{"condition": "Index > 50", "threshold": "50"}]'::jsonb,
   ARRAY['region', 'municipality']::text[], true),

  (48, 'teacher_shortage_index', 'Lärarbrist', 'karnsystem_funktion',
   'Andel undervisning av obehöriga lärare',
   'Mäter utbildningssystemets kapacitet.',
   '%', true,
   '[{"condition": "Andel > 20%", "threshold": "20"}]'::jsonb,
   ARRAY['subject', 'region', 'school_type']::text[], true),

-- BLOCK: Healthcare System
  (49, 'healthcare_queue_median', 'Vårdkötid (median)', 'karnsystem_funktion',
   'Medianväntetid från remiss till behandling',
   'Mäter vårdtillgänglighet och systemkapacitet.',
   'dagar', true,
   '[{"condition": "Väntetid > 90 dagar", "threshold": "90"}]'::jsonb,
   ARRAY['treatment_type', 'region']::text[], true),

  (50, 'avoidable_mortality_rate', 'Undvikbar dödlighet', 'demografi_halsa',
   'Dödsfall som kunde förhindrats med optimal vård, per 100 000',
   'Mäter vårdkvalitet och tillgänglighet.',
   'per 100 000', true,
   '[{"condition": "Rate > EU-medel"}]'::jsonb,
   ARRAY['cause', 'region', 'age']::text[], true),

-- BLOCK: Housing & Urban Reality
  (51, 'housing_cost_burden', 'Boendekostnadsbörda', 'ekonomisk_barkraft',
   'Andel av disponibel inkomst som går till boende',
   'Mäter bostadsmarknadens tillgänglighet.',
   '%', true,
   '[{"condition": "Andel > 40%", "threshold": "40"}]'::jsonb,
   ARRAY['income_decile', 'region', 'municipality', 'tenure_type']::text[], true),

  (52, 'residential_segregation_index', 'Boendesegregation', 'social_stabilitet',
   'Dissimilaritetsindex för bostadsområden',
   'Mäter geografisk separation mellan grupper.',
   'index 0-100', true,
   '[{"condition": "Index > 50", "threshold": "50"}]'::jsonb,
   ARRAY['region', 'municipality']::text[], true),

  (53, 'homelessness_rate', 'Hemlöshet', 'social_stabilitet',
   'Antal hemlösa per 10 000 invånare',
   'Mäter extrem bostadsbrist och social utslagning.',
   'per 10 000', true,
   '[{"condition": "Ökning > 10% per år"}]'::jsonb,
   ARRAY['category', 'region', 'municipality']::text[], true),

-- BLOCK: Democracy & Trust
  (54, 'institutional_trust_index', 'Institutionsförtroende', 'systemrisk_styrning',
   'Andel med förtroende för riksdag, polis, domstolar',
   'Mäter demokratisk legitimitet och samhällssammanhållning.',
   '%', false,
   '[{"condition": "Förtroende < 40%", "threshold": "40"}]'::jsonb,
   ARRAY['institution', 'demographic_group', 'region']::text[], true),

  (55, 'voter_turnout_gap', 'Valdeltagandegap', 'social_stabilitet',
   'Skillnad i valdeltagande mellan stadsdelar/grupper',
   'Mäter demokratisk representation.',
   'procentenheter', true,
   '[{"condition": "Gap > 20 procentenheter", "threshold": "20"}]'::jsonb,
   ARRAY['election_type', 'region', 'municipality']::text[], true),

  (56, 'media_trust_polarization', 'Mediepolarisering', 'social_stabilitet',
   'Spridning i medieförtroende mellan politiska grupper',
   'Mäter informationslandskapet och filterbubblor.',
   'standardavvikelse', true,
   '[{"condition": "SD > 25"}]'::jsonb,
   ARRAY['media_type', 'political_affiliation']::text[], true)

ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  rationale = EXCLUDED.rationale,
  breakdown_dimensions = EXCLUDED.breakdown_dimensions,
  is_active = EXCLUDED.is_active;