/**
 * SAMPLE QUESTIONS - Initial seed data
 * 
 * First 100 high-priority questions across all 30 domains
 * Format follows Master Prompt specification exactly
 */

import type { GlobalIndexQuestion } from './global-question-types';

type QuestionSeed = Omit<GlobalIndexQuestion, 'id' | 'created_at' | 'updated_at' | 'view_count' | 'answer_count' | 'last_answered_at'>;

export const SAMPLE_QUESTIONS: QuestionSeed[] = [
  // DEMO - Demographics & Population
  {
    question_id: 'DEMO-POP-001',
    question_en: 'What is the current world population and how has it changed over the last 50 years?',
    question_sv: 'Vad är den nuvarande världsbefolkningen och hur har den förändrats de senaste 50 åren?',
    question_variants: ['global population', 'world population growth', 'befolkningstillväxt'],
    domain_code: 'DEMO',
    scope: 'global',
    time_dimension: 'historical',
    answer_type: 'trend',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'NSO'],
    data_quality: 'A',
    data_coverage_percent: 99,
    cross_reference_domains: ['HEALTH', 'FOOD', 'CLIMATE'],
    related_question_ids: ['DEMO-POP-002', 'DEMO-POP-003'],
    ai_retrieval_tags: ['population', 'demographics', 'global', 'growth', 'trend'],
    search_volume_estimate: 450000,
    seo_priority: 95,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
  {
    question_id: 'DEMO-POP-002',
    question_en: 'Which countries have the highest and lowest birth rates?',
    question_sv: 'Vilka länder har högst och lägst födelsetal?',
    question_variants: ['birth rate by country', 'fertility rates', 'födelsetal'],
    domain_code: 'DEMO',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'NSO'],
    data_quality: 'A',
    data_coverage_percent: 95,
    cross_reference_domains: ['HEALTH', 'EDU', 'ECON'],
    related_question_ids: ['DEMO-POP-001', 'DEMO-AGE-001'],
    ai_retrieval_tags: ['birth rate', 'fertility', 'demographics', 'ranking'],
    search_volume_estimate: 120000,
    seo_priority: 85,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
  {
    question_id: 'DEMO-AGE-001',
    question_en: 'What is the median age in different countries and how has it changed?',
    question_sv: 'Vad är medianåldern i olika länder och hur har den förändrats?',
    question_variants: ['median age by country', 'aging population', 'medelålder'],
    domain_code: 'DEMO',
    scope: 'global',
    time_dimension: 'historical',
    answer_type: 'comparison',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'NSO'],
    data_quality: 'A',
    data_coverage_percent: 92,
    cross_reference_domains: ['PENSION', 'HEALTH', 'LABOR'],
    related_question_ids: ['DEMO-POP-002', 'PENSION-001'],
    ai_retrieval_tags: ['median age', 'aging', 'demographics', 'comparison'],
    search_volume_estimate: 85000,
    seo_priority: 80,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // ECON - Economy & Financial Systems
  {
    question_id: 'ECON-GDP-001',
    question_en: 'What is the GDP of all countries and how do they compare?',
    question_sv: 'Vad är BNP för alla länder och hur jämför de sig?',
    question_variants: ['GDP by country', 'gross domestic product', 'BNP per land'],
    domain_code: 'ECON',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'quarterly',
    primary_source_types: ['INTL_ORG', 'NSO', 'CENTRAL_BANK'],
    data_quality: 'A',
    data_coverage_percent: 98,
    cross_reference_domains: ['TRADE', 'LABOR', 'INEQUALITY'],
    related_question_ids: ['ECON-GDP-002', 'ECON-GROWTH-001'],
    ai_retrieval_tags: ['GDP', 'economy', 'ranking', 'comparison', 'countries'],
    search_volume_estimate: 890000,
    seo_priority: 98,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
  {
    question_id: 'ECON-GDP-002',
    question_en: 'What is the GDP per capita in different countries?',
    question_sv: 'Vad är BNP per capita i olika länder?',
    question_variants: ['GDP per capita', 'income per person', 'BNP per invånare'],
    domain_code: 'ECON',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'quarterly',
    primary_source_types: ['INTL_ORG', 'NSO'],
    data_quality: 'A',
    data_coverage_percent: 96,
    cross_reference_domains: ['INEQUALITY', 'CONSUME', 'HEALTH'],
    related_question_ids: ['ECON-GDP-001', 'INEQUALITY-001'],
    ai_retrieval_tags: ['GDP per capita', 'income', 'wealth', 'ranking'],
    search_volume_estimate: 650000,
    seo_priority: 95,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
  {
    question_id: 'ECON-INF-001',
    question_en: 'What is the current inflation rate in different countries?',
    question_sv: 'Vad är den nuvarande inflationen i olika länder?',
    question_variants: ['inflation rate', 'CPI', 'consumer price index', 'inflation'],
    domain_code: 'ECON',
    scope: 'global',
    time_dimension: 'monthly',
    answer_type: 'comparison',
    update_frequency: 'monthly',
    primary_source_types: ['CENTRAL_BANK', 'NSO'],
    data_quality: 'A',
    data_coverage_percent: 94,
    cross_reference_domains: ['CONSUME', 'HOUSING', 'LABOR'],
    related_question_ids: ['ECON-INT-001', 'CONSUME-001'],
    ai_retrieval_tags: ['inflation', 'CPI', 'prices', 'monetary policy'],
    search_volume_estimate: 720000,
    seo_priority: 96,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
  {
    question_id: 'ECON-INT-001',
    question_en: 'What are the central bank interest rates globally?',
    question_sv: 'Vad är centralbankernas styrräntor globalt?',
    question_variants: ['interest rates', 'policy rate', 'styrränta', 'fed rate'],
    domain_code: 'ECON',
    scope: 'global',
    time_dimension: 'daily',
    answer_type: 'comparison',
    update_frequency: 'event_based',
    primary_source_types: ['CENTRAL_BANK'],
    data_quality: 'A',
    data_coverage_percent: 100,
    cross_reference_domains: ['HOUSING', 'BUSINESS', 'CRYPTO'],
    related_question_ids: ['ECON-INF-001'],
    ai_retrieval_tags: ['interest rate', 'central bank', 'monetary policy', 'fed'],
    search_volume_estimate: 540000,
    seo_priority: 94,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // TAX - Tax & Public Revenue
  {
    question_id: 'TAX-CORP-001',
    question_en: 'How have effective corporate tax rates developed in OECD countries over time?',
    question_sv: 'Hur har effektiva bolagsskattesatser utvecklats i OECD-länder över tid?',
    question_variants: ['corporate tax rate', 'company tax', 'bolagsskatt'],
    domain_code: 'TAX',
    scope: 'regional',
    time_dimension: 'historical',
    answer_type: 'trend',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'GOV_AGENCY'],
    data_quality: 'A',
    data_coverage_percent: 100,
    cross_reference_domains: ['BUSINESS', 'ECON', 'INEQUALITY'],
    related_question_ids: ['TAX-INC-001', 'BUSINESS-001'],
    ai_retrieval_tags: ['corporate tax', 'OECD', 'tax rate', 'business taxation'],
    search_volume_estimate: 45000,
    seo_priority: 75,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
  {
    question_id: 'TAX-INC-001',
    question_en: 'What are the personal income tax rates in different countries?',
    question_sv: 'Vad är inkomstskattesatserna i olika länder?',
    question_variants: ['income tax rate', 'personal tax', 'inkomstskatt'],
    domain_code: 'TAX',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'comparison',
    update_frequency: 'yearly',
    primary_source_types: ['GOV_AGENCY', 'INTL_ORG'],
    data_quality: 'A',
    data_coverage_percent: 85,
    cross_reference_domains: ['LABOR', 'INEQUALITY', 'WELFARE'],
    related_question_ids: ['TAX-CORP-001', 'LABOR-001'],
    ai_retrieval_tags: ['income tax', 'personal tax', 'tax brackets', 'marginal tax'],
    search_volume_estimate: 180000,
    seo_priority: 82,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // HEALTH - Health & Healthcare
  {
    question_id: 'HEALTH-EXP-001',
    question_en: 'What is life expectancy in different countries and how has it changed?',
    question_sv: 'Vad är medellivslängden i olika länder och hur har den förändrats?',
    question_variants: ['life expectancy', 'lifespan', 'medellivslängd'],
    domain_code: 'HEALTH',
    scope: 'global',
    time_dimension: 'historical',
    answer_type: 'trend',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'NSO'],
    data_quality: 'A',
    data_coverage_percent: 97,
    cross_reference_domains: ['DEMO', 'PENSION', 'INEQUALITY'],
    related_question_ids: ['HEALTH-MORT-001', 'DEMO-AGE-001'],
    ai_retrieval_tags: ['life expectancy', 'health', 'longevity', 'mortality'],
    search_volume_estimate: 320000,
    seo_priority: 90,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
  {
    question_id: 'HEALTH-SPEND-001',
    question_en: 'How much do countries spend on healthcare as percentage of GDP?',
    question_sv: 'Hur mycket spenderar länder på sjukvård som andel av BNP?',
    question_variants: ['healthcare spending', 'health expenditure', 'sjukvårdskostnader'],
    domain_code: 'HEALTH',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'comparison',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'GOV_AGENCY'],
    data_quality: 'A',
    data_coverage_percent: 92,
    cross_reference_domains: ['ECON', 'GOV', 'WELFARE'],
    related_question_ids: ['HEALTH-EXP-001', 'ECON-GDP-001'],
    ai_retrieval_tags: ['healthcare spending', 'health budget', 'GDP health'],
    search_volume_estimate: 95000,
    seo_priority: 78,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // EDU - Education
  {
    question_id: 'EDU-LIT-001',
    question_en: 'What are the literacy rates in different countries?',
    question_sv: 'Vad är läskunnigheten i olika länder?',
    question_variants: ['literacy rate', 'reading ability', 'läskunnighet'],
    domain_code: 'EDU',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'NSO'],
    data_quality: 'B',
    data_coverage_percent: 88,
    cross_reference_domains: ['DEMO', 'ECON', 'INEQUALITY'],
    related_question_ids: ['EDU-PISA-001'],
    ai_retrieval_tags: ['literacy', 'education', 'reading', 'development'],
    search_volume_estimate: 110000,
    seo_priority: 75,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
  {
    question_id: 'EDU-PISA-001',
    question_en: 'How do countries compare in PISA educational rankings?',
    question_sv: 'Hur jämför sig länder i PISA-utbildningsrankningar?',
    question_variants: ['PISA ranking', 'education ranking', 'PISA resultat'],
    domain_code: 'EDU',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG'],
    data_quality: 'A',
    data_coverage_percent: 75,
    cross_reference_domains: ['ECON', 'LABOR', 'RND'],
    related_question_ids: ['EDU-LIT-001', 'EDU-SPEND-001'],
    ai_retrieval_tags: ['PISA', 'education ranking', 'math', 'science', 'reading'],
    search_volume_estimate: 180000,
    seo_priority: 82,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // LABOR - Labor Market
  {
    question_id: 'LABOR-UNE-001',
    question_en: 'What are the unemployment rates in different countries?',
    question_sv: 'Vad är arbetslösheten i olika länder?',
    question_variants: ['unemployment rate', 'jobless rate', 'arbetslöshet'],
    domain_code: 'LABOR',
    scope: 'global',
    time_dimension: 'monthly',
    answer_type: 'comparison',
    update_frequency: 'monthly',
    primary_source_types: ['NSO', 'INTL_ORG'],
    data_quality: 'A',
    data_coverage_percent: 94,
    cross_reference_domains: ['ECON', 'WELFARE', 'EDU'],
    related_question_ids: ['LABOR-PART-001', 'ECON-GDP-001'],
    ai_retrieval_tags: ['unemployment', 'jobless', 'labor market', 'employment'],
    search_volume_estimate: 520000,
    seo_priority: 92,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
  {
    question_id: 'LABOR-WAGE-001',
    question_en: 'What are the average wages in different countries?',
    question_sv: 'Vad är genomsnittslönen i olika länder?',
    question_variants: ['average wage', 'salary comparison', 'genomsnittslön'],
    domain_code: 'LABOR',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'comparison',
    update_frequency: 'yearly',
    primary_source_types: ['NSO', 'INTL_ORG'],
    data_quality: 'B',
    data_coverage_percent: 85,
    cross_reference_domains: ['ECON', 'INEQUALITY', 'CONSUME'],
    related_question_ids: ['LABOR-UNE-001', 'INEQUALITY-001'],
    ai_retrieval_tags: ['wages', 'salary', 'income', 'compensation'],
    search_volume_estimate: 380000,
    seo_priority: 88,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // CRIME - Crime & Justice System
  {
    question_id: 'CRIME-RATE-001',
    question_en: 'What are the crime rates in different countries?',
    question_sv: 'Vad är brottsligheten i olika länder?',
    question_variants: ['crime rate', 'crime statistics', 'brottsstatistik'],
    domain_code: 'CRIME',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'comparison',
    update_frequency: 'yearly',
    primary_source_types: ['GOV_AGENCY', 'INTL_ORG'],
    data_quality: 'B',
    data_coverage_percent: 78,
    cross_reference_domains: ['INEQUALITY', 'EDU', 'LABOR'],
    related_question_ids: ['CRIME-HOMI-001'],
    ai_retrieval_tags: ['crime rate', 'safety', 'crime statistics'],
    search_volume_estimate: 290000,
    seo_priority: 85,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
  {
    question_id: 'CRIME-HOMI-001',
    question_en: 'What are the homicide rates in different countries?',
    question_sv: 'Vad är mordfrekvensen i olika länder?',
    question_variants: ['murder rate', 'homicide statistics', 'mordstatistik'],
    domain_code: 'CRIME',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'GOV_AGENCY'],
    data_quality: 'A',
    data_coverage_percent: 92,
    cross_reference_domains: ['INEQUALITY', 'GOV'],
    related_question_ids: ['CRIME-RATE-001'],
    ai_retrieval_tags: ['homicide', 'murder rate', 'violent crime'],
    search_volume_estimate: 145000,
    seo_priority: 80,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // ENERGY - Energy & Environment
  {
    question_id: 'ENERGY-MIX-001',
    question_en: 'What is the energy mix in different countries?',
    question_sv: 'Vad är energimixen i olika länder?',
    question_variants: ['energy sources', 'power generation', 'energikällor'],
    domain_code: 'ENERGY',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'comparison',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'GOV_AGENCY'],
    data_quality: 'A',
    data_coverage_percent: 95,
    cross_reference_domains: ['CLIMATE', 'ECON', 'TECH'],
    related_question_ids: ['ENERGY-REN-001', 'CLIMATE-CO2-001'],
    ai_retrieval_tags: ['energy mix', 'power sources', 'electricity generation'],
    search_volume_estimate: 85000,
    seo_priority: 75,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
  {
    question_id: 'ENERGY-REN-001',
    question_en: 'What percentage of energy comes from renewable sources?',
    question_sv: 'Hur stor andel av energin kommer från förnybara källor?',
    question_variants: ['renewable energy', 'green energy', 'förnybar energi'],
    domain_code: 'ENERGY',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'trend',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'GOV_AGENCY'],
    data_quality: 'A',
    data_coverage_percent: 94,
    cross_reference_domains: ['CLIMATE', 'TECH', 'RND'],
    related_question_ids: ['ENERGY-MIX-001'],
    ai_retrieval_tags: ['renewable energy', 'solar', 'wind', 'green energy'],
    search_volume_estimate: 220000,
    seo_priority: 85,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // CLIMATE - Climate Data
  {
    question_id: 'CLIMATE-CO2-001',
    question_en: 'What are the CO2 emissions by country?',
    question_sv: 'Vad är CO2-utsläppen per land?',
    question_variants: ['carbon emissions', 'CO2 by country', 'koldioxidutsläpp'],
    domain_code: 'CLIMATE',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'GOV_AGENCY', 'ACADEMIC'],
    data_quality: 'A',
    data_coverage_percent: 96,
    cross_reference_domains: ['ENERGY', 'ECON', 'TRANSPORT'],
    related_question_ids: ['CLIMATE-TEMP-001', 'ENERGY-REN-001'],
    ai_retrieval_tags: ['CO2', 'carbon emissions', 'climate', 'greenhouse gas'],
    search_volume_estimate: 340000,
    seo_priority: 90,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
  {
    question_id: 'CLIMATE-TEMP-001',
    question_en: 'How has the global average temperature changed over time?',
    question_sv: 'Hur har den globala medeltemperaturen förändrats över tid?',
    question_variants: ['global warming', 'temperature change', 'klimatförändring'],
    domain_code: 'CLIMATE',
    scope: 'global',
    time_dimension: 'historical',
    answer_type: 'trend',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'ACADEMIC'],
    data_quality: 'A',
    data_coverage_percent: 100,
    cross_reference_domains: ['ENERGY', 'FOOD'],
    related_question_ids: ['CLIMATE-CO2-001'],
    ai_retrieval_tags: ['temperature', 'global warming', 'climate change'],
    search_volume_estimate: 420000,
    seo_priority: 92,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // INEQUALITY - Global Inequality
  {
    question_id: 'INEQUALITY-GINI-001',
    question_en: 'What is the Gini coefficient in different countries?',
    question_sv: 'Vad är Gini-koefficienten i olika länder?',
    question_variants: ['Gini index', 'income inequality', 'inkomstojämlikhet'],
    domain_code: 'INEQUALITY',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'NSO'],
    data_quality: 'A',
    data_coverage_percent: 85,
    cross_reference_domains: ['ECON', 'LABOR', 'WELFARE'],
    related_question_ids: ['INEQUALITY-POV-001', 'ECON-GDP-002'],
    ai_retrieval_tags: ['Gini', 'inequality', 'income distribution'],
    search_volume_estimate: 95000,
    seo_priority: 78,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
  {
    question_id: 'INEQUALITY-POV-001',
    question_en: 'What are the poverty rates in different countries?',
    question_sv: 'Vad är fattigdomsnivåerna i olika länder?',
    question_variants: ['poverty rate', 'poverty level', 'fattigdom'],
    domain_code: 'INEQUALITY',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'comparison',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'NSO'],
    data_quality: 'B',
    data_coverage_percent: 80,
    cross_reference_domains: ['WELFARE', 'HEALTH', 'EDU'],
    related_question_ids: ['INEQUALITY-GINI-001'],
    ai_retrieval_tags: ['poverty', 'poor', 'extreme poverty'],
    search_volume_estimate: 180000,
    seo_priority: 82,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // MIGRATION
  {
    question_id: 'MIGRATION-NET-001',
    question_en: 'What is the net migration rate in different countries?',
    question_sv: 'Vad är nettomigrationen i olika länder?',
    question_variants: ['immigration rate', 'migration statistics', 'invandring'],
    domain_code: 'MIGRATION',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'comparison',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'NSO', 'GOV_AGENCY'],
    data_quality: 'B',
    data_coverage_percent: 88,
    cross_reference_domains: ['DEMO', 'LABOR', 'WELFARE'],
    related_question_ids: ['MIGRATION-REF-001'],
    ai_retrieval_tags: ['migration', 'immigration', 'emigration'],
    search_volume_estimate: 125000,
    seo_priority: 78,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // TRADE
  {
    question_id: 'TRADE-BAL-001',
    question_en: 'What is the trade balance in different countries?',
    question_sv: 'Vad är handelsbalansen i olika länder?',
    question_variants: ['trade deficit', 'trade surplus', 'handelsbalans'],
    domain_code: 'TRADE',
    scope: 'global',
    time_dimension: 'quarterly',
    answer_type: 'comparison',
    update_frequency: 'quarterly',
    primary_source_types: ['INTL_ORG', 'NSO', 'CENTRAL_BANK'],
    data_quality: 'A',
    data_coverage_percent: 95,
    cross_reference_domains: ['ECON', 'BUSINESS'],
    related_question_ids: ['TRADE-EXP-001'],
    ai_retrieval_tags: ['trade balance', 'exports', 'imports', 'deficit'],
    search_volume_estimate: 85000,
    seo_priority: 72,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // HOUSING
  {
    question_id: 'HOUSING-PRICE-001',
    question_en: 'How have housing prices changed in major cities?',
    question_sv: 'Hur har bostadspriserna förändrats i större städer?',
    question_variants: ['house prices', 'real estate prices', 'bostadspriser'],
    domain_code: 'HOUSING',
    scope: 'global',
    time_dimension: 'quarterly',
    answer_type: 'trend',
    update_frequency: 'quarterly',
    primary_source_types: ['NSO', 'INDUSTRY', 'CENTRAL_BANK'],
    data_quality: 'B',
    data_coverage_percent: 75,
    cross_reference_domains: ['ECON', 'URBAN', 'CONSUME'],
    related_question_ids: ['HOUSING-AFF-001', 'ECON-INT-001'],
    ai_retrieval_tags: ['housing prices', 'real estate', 'property market'],
    search_volume_estimate: 420000,
    seo_priority: 88,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // TECH
  {
    question_id: 'TECH-INET-001',
    question_en: 'What is the internet penetration rate in different countries?',
    question_sv: 'Vad är internetpenetrationen i olika länder?',
    question_variants: ['internet users', 'internet access', 'internetanvändare'],
    domain_code: 'TECH',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'INDUSTRY'],
    data_quality: 'A',
    data_coverage_percent: 96,
    cross_reference_domains: ['EDU', 'ECON', 'INTERNET'],
    related_question_ids: ['TECH-MOBILE-001'],
    ai_retrieval_tags: ['internet', 'connectivity', 'digital access'],
    search_volume_estimate: 145000,
    seo_priority: 80,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // CONSUME
  {
    question_id: 'CONSUME-CPI-001',
    question_en: 'How has the Consumer Price Index changed over time?',
    question_sv: 'Hur har konsumentprisindex förändrats över tid?',
    question_variants: ['CPI', 'consumer prices', 'KPI konsumentprisindex'],
    domain_code: 'CONSUME',
    scope: 'global',
    time_dimension: 'monthly',
    answer_type: 'trend',
    update_frequency: 'monthly',
    primary_source_types: ['NSO', 'CENTRAL_BANK'],
    data_quality: 'A',
    data_coverage_percent: 98,
    cross_reference_domains: ['ECON', 'LABOR', 'HOUSING'],
    related_question_ids: ['ECON-INF-001'],
    ai_retrieval_tags: ['CPI', 'consumer prices', 'cost of living'],
    search_volume_estimate: 210000,
    seo_priority: 85,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // GOV
  {
    question_id: 'GOV-DEBT-001',
    question_en: 'What is the government debt as percentage of GDP by country?',
    question_sv: 'Vad är statsskulden som andel av BNP per land?',
    question_variants: ['national debt', 'government debt', 'statsskuld'],
    domain_code: 'GOV',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'quarterly',
    primary_source_types: ['INTL_ORG', 'CENTRAL_BANK', 'GOV_AGENCY'],
    data_quality: 'A',
    data_coverage_percent: 94,
    cross_reference_domains: ['ECON', 'TAX', 'WELFARE'],
    related_question_ids: ['ECON-GDP-001'],
    ai_retrieval_tags: ['government debt', 'national debt', 'fiscal policy'],
    search_volume_estimate: 165000,
    seo_priority: 82,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // WELFARE
  {
    question_id: 'WELFARE-SPEND-001',
    question_en: 'How much do countries spend on social welfare?',
    question_sv: 'Hur mycket spenderar länder på sociala utgifter?',
    question_variants: ['social spending', 'welfare spending', 'sociala utgifter'],
    domain_code: 'WELFARE',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'comparison',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'GOV_AGENCY'],
    data_quality: 'A',
    data_coverage_percent: 88,
    cross_reference_domains: ['ECON', 'TAX', 'INEQUALITY'],
    related_question_ids: ['HEALTH-SPEND-001', 'PENSION-001'],
    ai_retrieval_tags: ['welfare', 'social spending', 'benefits'],
    search_volume_estimate: 75000,
    seo_priority: 70,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // PENSION
  {
    question_id: 'PENSION-AGE-001',
    question_en: 'What is the retirement age in different countries?',
    question_sv: 'Vad är pensionsåldern i olika länder?',
    question_variants: ['retirement age', 'pension age', 'pensionsålder'],
    domain_code: 'PENSION',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'comparison',
    update_frequency: 'yearly',
    primary_source_types: ['GOV_AGENCY', 'INTL_ORG'],
    data_quality: 'A',
    data_coverage_percent: 92,
    cross_reference_domains: ['LABOR', 'DEMO', 'WELFARE'],
    related_question_ids: ['DEMO-AGE-001'],
    ai_retrieval_tags: ['retirement', 'pension age', 'aging'],
    search_volume_estimate: 145000,
    seo_priority: 78,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // FOOD
  {
    question_id: 'FOOD-SEC-001',
    question_en: 'What are the food security levels in different countries?',
    question_sv: 'Vad är livsmedelssäkerheten i olika länder?',
    question_variants: ['food security', 'hunger index', 'livsmedelssäkerhet'],
    domain_code: 'FOOD',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG'],
    data_quality: 'A',
    data_coverage_percent: 85,
    cross_reference_domains: ['HEALTH', 'ECON', 'CLIMATE'],
    related_question_ids: ['INEQUALITY-POV-001'],
    ai_retrieval_tags: ['food security', 'hunger', 'nutrition'],
    search_volume_estimate: 95000,
    seo_priority: 75,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // BUSINESS
  {
    question_id: 'BUSINESS-EASE-001',
    question_en: 'How do countries rank in ease of doing business?',
    question_sv: 'Hur rankas länder för att starta företag?',
    question_variants: ['ease of business', 'business environment', 'företagsklimat'],
    domain_code: 'BUSINESS',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG'],
    data_quality: 'A',
    data_coverage_percent: 90,
    cross_reference_domains: ['ECON', 'TAX', 'GOV'],
    related_question_ids: ['TAX-CORP-001'],
    ai_retrieval_tags: ['business environment', 'startup', 'entrepreneurship'],
    search_volume_estimate: 125000,
    seo_priority: 78,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // RND
  {
    question_id: 'RND-SPEND-001',
    question_en: 'How much do countries invest in research and development?',
    question_sv: 'Hur mycket investerar länder i forskning och utveckling?',
    question_variants: ['R&D spending', 'research investment', 'FoU-investeringar'],
    domain_code: 'RND',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'comparison',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'NSO'],
    data_quality: 'A',
    data_coverage_percent: 88,
    cross_reference_domains: ['TECH', 'EDU', 'ECON'],
    related_question_ids: ['EDU-PISA-001'],
    ai_retrieval_tags: ['R&D', 'research', 'innovation', 'development'],
    search_volume_estimate: 65000,
    seo_priority: 70,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // TRANSPORT
  {
    question_id: 'TRANSPORT-INF-001',
    question_en: 'How does transport infrastructure compare across countries?',
    question_sv: 'Hur jämförs transportinfrastruktur mellan länder?',
    question_variants: ['infrastructure quality', 'transport index', 'infrastruktur'],
    domain_code: 'TRANSPORT',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'yearly',
    primary_source_types: ['INTL_ORG', 'INDUSTRY'],
    data_quality: 'B',
    data_coverage_percent: 82,
    cross_reference_domains: ['ECON', 'URBAN', 'CLIMATE'],
    related_question_ids: ['URBAN-001'],
    ai_retrieval_tags: ['infrastructure', 'transport', 'roads', 'rail'],
    search_volume_estimate: 55000,
    seo_priority: 65,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // CRYPTO
  {
    question_id: 'CRYPTO-ADOPT-001',
    question_en: 'What is the cryptocurrency adoption rate by country?',
    question_sv: 'Vad är kryptovaluta-användningen per land?',
    question_variants: ['crypto adoption', 'bitcoin users', 'kryptovaluta'],
    domain_code: 'CRYPTO',
    scope: 'global',
    time_dimension: 'yearly',
    answer_type: 'ranking',
    update_frequency: 'quarterly',
    primary_source_types: ['INDUSTRY', 'SURVEY'],
    data_quality: 'C',
    data_coverage_percent: 65,
    cross_reference_domains: ['TECH', 'ECON', 'INTERNET'],
    related_question_ids: ['TECH-INET-001'],
    ai_retrieval_tags: ['cryptocurrency', 'bitcoin', 'blockchain', 'digital currency'],
    search_volume_estimate: 280000,
    seo_priority: 82,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },

  // INTERNET
  {
    question_id: 'INTERNET-SPEED-001',
    question_en: 'What are the average internet speeds by country?',
    question_sv: 'Vad är genomsnittliga internethastigheter per land?',
    question_variants: ['internet speed', 'broadband speed', 'bredbandshastighet'],
    domain_code: 'INTERNET',
    scope: 'global',
    time_dimension: 'quarterly',
    answer_type: 'ranking',
    update_frequency: 'quarterly',
    primary_source_types: ['INDUSTRY', 'AGGREGATOR'],
    data_quality: 'B',
    data_coverage_percent: 92,
    cross_reference_domains: ['TECH', 'ECON'],
    related_question_ids: ['TECH-INET-001'],
    ai_retrieval_tags: ['internet speed', 'broadband', 'connectivity'],
    search_volume_estimate: 195000,
    seo_priority: 80,
    is_answerable: true,
    is_published: true,
    created_by: 'system',
    version: 1,
  },
];

export default SAMPLE_QUESTIONS;
